const Menu = [
    {
        id: 1,
        image: "images/aloo-pakoda.jpg",
        name: "Aloo Pakoda",
        category: "Breakfast",
        price: "25₹",
        description: "Aloo pakora are soft melt-in-the-mouth fried potato fritters coated in a delicious, golden, crispy batter. It is also known as potato bajji and has always been one of my favorite tea-time snacks. Make this awesome vegan potato snack in less than 30 minutes.",
    },
    {
        id: 2,
        image: "images/biryani.jpg",
        name: "Biryani",
        category: "Dinner",
        price: "80₹",
        description: "Biryani is a mixed rice dish, mainly popular in South Asia. It is made with rice, some type of meat (chicken, goat, lamb, beef, prawn, or fish) and spices.",
    },
    {
        id: 3,
        image: "images/cake.jpg",
        name: "Chocolate Cake",
        category: "Desert",
        price: "45₹",
        description: "Chocolate cake or chocolate gâteau (from French: gâteau au chocolat) is a cake flavored with melted chocolate, cocoa powder, or both. Chocolate cake is made with chocolate. It can also include other ingredients. These include fudge, vanilla creme, and other sweeteners.",
    },
    {
        id: 4,
        image: "images/chola-bhatoora.jpg",
        name: "Chola-Bhatoora",
        category: "Lunch",
        price: "55₹",
        description: "Chole bhature is a food dish popular in the northern areas of the Indian subcontinent. It is a combination of chana masala (spicy white chickpeas) and bhatura/puri, a deep-fried bread made from maida.",
    },
    {
        id: 5,
        image: "images/dosa.jpg",
        name: "South Indian Dosa",
        category: "Dinner",
        price: "90₹",
        description: "It is a type of pancake made from fermented batter of rice and blackgram. The literary references to dosa date back to the 1st century AD. The place of origin of dosa is debatable but traditionally accepted to be Udupi, a town in the state of Karnataka.",
    },
    {
        id: 6,
        image: "images/idli.jpg",
        name: "South Indian Idli",
        category: "Lunch",
        price: "65₹",
        description: "Idli or idly (/ɪdliː/) (plural: idlis) is a type of savoury rice cake, originating from South India, popular as a breakfast food in Southern India and in Sri Lanka.",
    },
    {
        id: 7,
        image: "images/lassi.jpg",
        name: "Lassi",
        category: "Desert",
        price: "90₹",
        description: "Lassi originated in the Punjab region of the Indian subcontinent. The word lassi means yogurt mixed with water in Punjabi. Lassi is prepared by blending yogurt, water, and spices. In Punjab, the yogurt is traditionally made from water buffalo milk.",
    },
    {
        id: 8,
        image: "images/maggi.jpg",
        name: "Maggie",
        category: "Lunch",
        price: "50₹",
        description: "Maggi noodles are dried noodles fused with oil, and sold with a packet of flavorings. These noodles are usually eaten after being cooked in boiling water for 3 to 5 minutes or eaten straight from the packet. Just boil the water, add the tastemaker and noodles and your maggi is ready within 2 to 3 minutes.",
    },
    {
        id: 9,
        image: "images/momos.jpg",
        name: "Momo's",
        category: "Breakfast",
        price: "20₹",
        description: "Momo was born on November 9, 1996 in Kyotanabe, Kyoto, Japan. Her family consists of her parents and older sister by two years, Hana Hirai. Momo started dancing at a very young age and decided to become a singer because of Amuro Namie and got into K-pop after watching Rain and Lee Hyori.",
    },
    {
        id: 10,
        image: "images/pizza.jpg",
        name: "Pizza",
        category: "Breakfast",
        price: "150₹",
        description: "Pizza (/ˈpiːtsə/ PEET-sə, Italian: [ˈpittsa]; Neapolitan: [ˈpittsə]) is a dish of Italian origin consisting of a usually round, flat base of leavened wheat-based dough topped with tomato, cheese, and often various other ingredients (such as anchovies, mushrooms, onions, olives, vegetables, meat, etc.)",
    },
    {
        id: 11,
        image: "images/rasgulla.jpg",
        name: "Rasgulla",
        category: "Desert",
        price: "20₹",
        description: "Rasgulla (literally syrup filled ball) is a syrupy dessert popular in the eastern part of South Asia. It is made from ball-shaped dumplings of chhena dough, cooked in light sugar syrup. This is done until the syrup permeates the dumplings.",
    },
    {
        id: 12,
        image: "images/samosa.jpg",
        name: "Samosa",
        category: "Breakfast",
        price: "10₹",
        description: "A samosa can be vegetarian or non-vegetarian, depending on the filling. The entire pastry is deep-fried in vegetable oil or (rarely) ghee to a golden brown. It is served hot, often with fresh green chutney, such as mint or coriander chutney, or tamarind chutney. It can also be prepared in a sweet form.",
    },
    {
        id: 13,
        image: "images/Chow-Mein.jpg",
        name: "Chow Mein",
        category: "Chinese",
        price: "85₹",
        description: "In American Chinese cuisine, it is a stir-fried dish consisting of noodles, meat (chicken being most common but pork, beef, shrimp or tofu sometimes being substituted), onions and celery. It is often served as a specific dish at westernized Chinese restaurants. Vegetarian or vegan chow mein is also common.",
    },
    {
        id: 14,
        image: "images/chat.jpg",
        name: "Chaat",
        category: "Indian",
        price: "120₹",
        description: "Chaat is an umbrella term for a wide range of roadside foods that usually feature some kind of fried dough with various ingredients that typically create a spicy, tangy, or salty flavour, though some chaat are sweet.",
    },
    {
        id: 15,
        image: "images/pie.jpg",
        name: "Key lime pie",
        category: "American",
        price: "100₹",
        description: "It is also known as the 'Mexican' or 'Key' lime in the Florida Keys. The fruits are round or elliptical in shape with a thin or thick rind depending on the variety. The fruits have very small neck, a flat base, and a small nipple at the apex. The highly acidic flesh is juicy with a distinct aroma and flavor.",
    },
];

export default Menu;